# Generated by Django 4.0.4 on 2022-05-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedbacck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbacck',
            new_name='Feedback',
        ),
    ]
